FROM ubuntu:23.10

LABEL author="Arkady"

RUN apt-get update

RUN apt-get install nginx -y

WORKDIR /var/www/html/

COPY ./dist/index.html /var/www/html/

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
